botio:
  i18nEnabled: true
spring:
  jpa:
    hibernate.ddl-auto: update
  application:
    name: BotIOSpring
  datasource:
    url: jdbc:mysql://localhost:3306/aisummarizer
    username: admin
    password: nimda
